# WARNING: Upgrade the k8s cluster can be risky. Make sure you know what you are doing.
# Read the guide: 'op/upgrade.md' .

# update kubectl binary
- hosts:
  - kube-master
  - kube-node
  - deploy
  roles:
  - prepare

# update etcd 
- hosts: etcd
  roles:
  - etcd

# update docker binary
- hosts:
  - kube-master
  - new-master
  - kube-node
  - new-node
  roles:
  - docker

# update masters
- hosts: 
  - kube-master
  - new-master
  roles:
  - kube-master
  - kube-node

# update nodes
- hosts: 
  - kube-node
  - new-node
  roles:
  - { role: kube-node, when: "DEPLOY_MODE != 'allinone'" }
